# Generated by Django 3.0.7 on 2021-11-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mesage',
            new_name='message',
        ),
    ]
